# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true

    session:
        enabled: false

    serializer:
        default_context:
            enable_max_depth: true

    php_errors:
        log: true

    router:
        resource: "%kernel.project_dir%/config/routes.yaml"
        type: yaml

when@test:
    framework:
        test: true
        session:
            enabled: false
