services:
  app:
    container_name: ${APP_NAME}.service.app
    restart: unless-stopped
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    env_file:
      - .env
    depends_on:
      - database
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    container_name: ${APP_NAME}.service.nginx
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - app
    volumes:
      - .:/var/www/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
    ports:
      - ${NGINX_HTTP_PORTS}
      - ${NGINX_HTTPS_PORTS}
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  database:
    container_name: ${APP_NAME}.service.db
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_DB_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      TZ: ${TIMEZONE}
    ports:
      - ${DATABASE_PORTS}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  node:
    container_name: ${APP_NAME}.service.node
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - app
    env_file:
      - .env
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
      - /var/www/app/node_modules
    ports:
      - ${NODE_JS_APP_PORTS}
    networks:
      - app_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  database_data:

networks:
  app_network:
